### ISSUE TITLE
Error when referencing file in page's folder rather than in an external folder

### ISSUE THREAD

**Issue by mikolajgolunski** [OliverO2/grav-plugin-responsive-images#1]
Plugin works great if images are held in a single folder such as `user/pages/images`. In that situation I can define path as `path: "images/image-*.jpg"`.
When trying to define path to the file in page's folder via `path: "image-*.jpg"` I get a php error `Argument 2 passed to Grav\Plugin\ResponsiveImagesExtension::imageURL() must be of the type string, null given` which is called from file `ResponsiveImagesExtension.php` line 241 followed from line 73. It seems like specifing a path to the file in page's folder in a way the Grav does it does not work.

I should probably mention that I've found this issue when working with modular page. I didn't try it yet on regular page.

**Comment by OliverO2** [comment]
Thanks for reporting! The error you are getting is a consequence of the plugin looking into a directory where there are no files matching the pattern.

To find the images' directory
1. the plugin uses Grav's resource locator if given a location starting with [_stream_](https://learn.getgrav.org/16/content/image-linking#php-streams) such as `image://` (see [Where to put your media files](https://learn.getgrav.org/16/content/media#where-to-put-your-media-files) for possible ways to specify a location),
1. otherwise it uses the given path, prepending Grav's base location plus `/user/pages/`.

Apparently, you'd prefer a [slug-relative](https://learn.getgrav.org/16/content/image-linking#slug-relative) or [directory-relative](https://learn.getgrav.org/16/content/image-linking#directory-relative) image link and the above strategy #2 gets in the way.

To enable page-relative image links and retain better compatibility with Grav, it seems reasonable to restrict strategy #2 to interpret only absolute paths relative to `/user/pages/`. Such a change would break backward compatibility for the plugin's users: Former relative paths lacking a _stream_ would then have to be converted to absolute paths.

I'll look into this, hopefully within two weeks or so.

**Comment by OliverO2** [comment]
Version 3.0.0 now supports page-relative image links and is in line with Grav's documentation on [Image Linking](https://learn.getgrav.org/16/content/image-linking).
